POST http://localhost:3001/api/patients/d2773598-f723-11e9-8f0b-362b9e1556/entries
Content-Type: application/json

{
    "type": "Hospital",
    "description": "Yearly control visit. Due to high cholesterol levels recommended to eat more vegetables.",
    "date": "2022-10-05",
    "specialist": "Dr. Smith",
    "diagnosisCodes": [
        "S62.5"
    ],
    "discharge": {
        "date": "2022-10-05",
        "criteria": "Patient feels well and is able to eat normal food."
    }
}