POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "John Doe",
    "dateOfBirth": "1990-01-01",
    "ssn": "123-45-6789",
    "gender": "male",
    "occupation": "Software Engineer"
}